//! Hover dictionary — @generated by tools/gen_hover_data.py from
//! pyregtab docs/rtl-reference.md. Do not edit; re-run the script
//! when the reference changes.

/// (token, markdown). Word tokens are upper-case; punctuation as-is.
pub static HOVER: &[(&str, &str)] = &[
    ("#", "**Tag `#'name'`**

User-defined tag attached to an item; `#'t'` in a constraint position matches tagged items, `!#'t'` — untagged."),
    ("$", "**Fragment `$NAME`**

Named fragment: declared in the preamble (`$N=[…]` / `$N={…}`), referenced as `[$N]` / `{$N}`. Expansion is a syntactic substitution."),
    ("*", "**Quantifier `*` / cardinality**

`?` — 0 or 1

`*` — 0 or more

`+` — 1 or more

`{n}` — exactly *n*

Provider cardinality:

`{n}` — at most *n*

`*` — unbounded"),
    ("+", "**Quantifier `+`**

`?` — 0 or 1

`*` — 0 or more

`+` — 1 or more

`{n}` — exactly *n*"),
    ("->", "**Action arrow `providers->OP`**

Applies the interpretation action `OP` to the anchor item, with candidate items supplied by the providers."),
    ("..", "**Range `a..b`**

Positional range: `C1..3`, `R+1..`, `P0..2`. An open end (`a..`) is unbounded."),
    ("?", "**Quantifier / condition marker**

`?` — 0 or 1

`*` — 0 or more

`+` — 1 or more

`{n}` — exactly *n*

After a cell match condition, `?` separates the condition from the content specification."),
    ("@", "**Constant AVP `@'ATTR'='VALUE'`**

Context-derived provider: a constant attribute–value pair."),
    ("ANCH", "**Setting `ANCH(n)`**

Use position *n* in the first record as the attribute name for all records"),
    ("ATTR", "**Item derivation directive `ATTR`**

Attribute-associated item"),
    ("AUX", "**Item derivation directive `AUX`**

Auxiliary item"),
    ("AV", "**Spatial constraint `AV`**

Candidate cells relative to the anchor *a*: `same_subcol(a) && row < row(a)`"),
    ("AVP", "**Interpretation action `AVP`**

`prov->AVP` — Associate anchor (VAL) with an attribute from the provider (ATTR)"),
    ("BLANK", "**Content constraint `BLANK`**

`blankStr()`

---

**Content constraint `!BLANK`**

`!blankStr()`"),
    ("BW", "**Spatial constraint `BW`**

Candidate cells relative to the anchor *a*: `same_subcol(a) && row > row(a)`"),
    ("C", "**Positional constraint `C…` (column)**

`Cn` — `col == n`

`C+n` / `C-n` — `col == col(a) + n`

`Ca..b` — `a ≤ col ≤ b` (absolute)`

`C+a..b` — `col(a)+a ≤ col ≤ col(a)+b` (relative)`"),
    ("CL", "**Spatial constraint `CL`**

Candidate cells relative to the anchor *a*: `same_cell(a)`"),
    ("COL", "**Spatial constraint `COL`**

Candidate cells relative to the anchor *a*: `same_col(a) && !same_cell(a)`"),
    ("EXT", "**Content constraint `EXT('name')`**

`Python item filter bound under `name` — see [External Python bindings](#external-python-bindings-extname)`

---

**External binding `EXT('name')`**

Resolved against host-runtime `Bindings` at compile time; while editing standalone files it is treated as always-true.

Cell match condition (`EXT('n') ?`, `[EXT('n')]`) → **Bindings.cell(name, …)** (Predicate<Cell>)

Provider constraint (`(ROW & EXT('n'))->REC`) → **Bindings.filter(name, …)** (BiPredicate<CellDerivedItem, CellDerivedItem>` (anchor, candidate))"),
    ("FILL", "**Interpretation action `FILL`**

`prov->FILL('/')` — Fill anchor value forward from provider, separated by *s*"),
    ("JOIN", "**Interpretation action `JOIN`**

`prov->JOIN` — Join item-based records: all items included, then dedup by named attribute (K=∅)

`prov->JOIN(0)` — Join with key positions K dropped from each joined record before dedup (e.g. `JOIN(0)` drops the anchor position)"),
    ("LC", "**String extractor `LC`**

To lower case"),
    ("LT", "**Spatial constraint `LT`**

Candidate cells relative to the anchor *a*: `same_subrow(a) && col < col(a)`"),
    ("NCL", "**Spatial constraint `NCL`**

Candidate cells relative to the anchor *a*: `!same_cell(a)`"),
    ("NORM", "**Setting `NORM`**

Apply whitespace normalisation to all field values after extraction

---

**String extractor `NORM`**

Trim + collapse internal whitespace"),
    ("P", "**Positional constraint `P…` (position-in-record)**

`Pn` — `index == n`

`P+n` / `P-n` — `index == index(a) + n`

`Pa..b` — `a ≤ index ≤ b`"),
    ("PREFIX", "**Interpretation action `PREFIX`**

`prov->PREFIX(' ')` — Prepend provider value to anchor, separated by *s*"),
    ("R", "**Positional constraint `R…` (row)**

`Rn` — `row == n`

`R+n` / `R-n` — `row == row(a) + n`"),
    ("REC", "**Interpretation action `REC`**

`prov->REC` — Anchor item → record entry; provider supplies additional field values

`()->REC` — Anchor item → single-field record (no additional providers; useful after `SUFFIX`/`PREFIX`/`FILL` has enriched the anchor value)

`prov->REC(n)` — Same + use attribute at position *n* as the record's attribute name

`prov->REC('s')` — Same + split field values by delimiter *s*"),
    ("REPL", "**String extractor `REPL(\"a\",\"b\")`**

Replace *a* with *b* (Java regex)"),
    ("ROW", "**Spatial constraint `ROW`**

Candidate cells relative to the anchor *a*: `same_row(a) && !same_cell(a)`"),
    ("RT", "**Spatial constraint `RT`**

Candidate cells relative to the anchor *a*: `same_subrow(a) && col > col(a)`"),
    ("SC", "**Spatial constraint `SC`**

Candidate cells relative to the anchor *a*: `same_subcol(a) && !same_cell(a)`"),
    ("SKIP", "**Item derivation directive `SKIP`**

No item derived (cell is consumed but ignored)"),
    ("SPLIT", "**Setting `SPLIT(\"s\")`**

Split all field values by delimiter *s* after extraction"),
    ("SR", "**Spatial constraint `SR`**

Candidate cells relative to the anchor *a*: `same_subrow(a) && !same_cell(a)`"),
    ("ST", "**Spatial constraint `ST`**

Candidate cells relative to the anchor *a*: `same_subtable(a) && !same_cell(a)`"),
    ("STR", "**Content constraint `STR`**

`sameStr(a)` (same string as the anchor)`"),
    ("SUBSTR", "**String extractor `SUBSTR(n,m)`**

Substring starting at position *n*, length *m*"),
    ("SUFFIX", "**Interpretation action `SUFFIX`**

`prov->SUFFIX(' ')` — Append provider value to anchor, separated by *s*"),
    ("TRIM", "**String extractor `TRIM`**

Strip leading/trailing whitespace only"),
    ("UC", "**String extractor `UC`**

To upper case"),
    ("VAL", "**Item derivation directive `VAL`**

Value-associated item"),
    ("^", "**Traversal order**

`-` — REVERSE_ROW_MAJOR

`^` — COLUMN_MAJOR

`-^` — REVERSE_COLUMN_MAJOR"),
    ("_", "**Item derivation directive `_`**

No item derived (cell is consumed but ignored)"),
    ("{N}", "**Quantifier `{n}` / cardinality**

`?` — 0 or 1

`*` — 0 or more

`+` — 1 or more

`{n}` — exactly *n*

Provider cardinality:

`{n}` — at most *n*

`*` — unbounded"),
];
